# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
# [[main]]
#     name = "标签 | Tags"
#     url = "/tags/"
#     weight = -90
#     [main.params]
#         icon = "tag"
#         newtab = true

# [[main]]
#     name = "搜索 | Search"
#     url = "/search/"
#     weight = -70
#     [main.params]
#         icon = "search"
#         newtab = true

# [[main]]
#     identifier = "stats"
#     name       = "统计"
#     url        = "/stats/"
#     weight     = 5
#     [main.params]
#         icon = "tag"


[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/wabi-sabi-c/Hugo_stack_blog"

    [social.params]
        icon = "brand-github"

# [[social]]
#     identifier = "twitter"
#     name       = "Twitter"
#     url        = "https://twitter.com"

#     [social.params]
#         icon = "brand-twitter"
